apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: entity-depl
spec:
  selector:
    matchLabels:
      app: entity
  template:
    metadata:
      labels:
        app: entity
    spec:
      containers:
        - name: entity
          image: 19127098/entity
          # imagePullPolicy: Always
          resources:
---
apiVersion: v1 
kind: Service 
metadata:
  name: entity-srv
spec:
  type: LoadBalancer
  selector: 
    app: entity   
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000
            
    