apiVersion: apps/v1
kind: Deployment 
metadata:
  name: user-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth
  template:
    metadata:
      labels:
        app: user-auth
    spec:
      containers:
        - name: user-auth
          image: 19127098/user-auth
          # imagePullPolicy: Always
          resources:
---
apiVersion: v1 
kind: Service 
metadata:
  name: user-auth-srv
spec:
  type: LoadBalancer
  selector: 
    app: user-auth   
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000